env_name : "Craftax-Coop-Symbolic"
agent_type : "cot"
seed : 2026
max_episode_steps : 50
model_id : "gpt-4o"
llm_temperature : 1.0
llm_max_tokens : 4096
max_retries : 5
retry_delay : 2
parallel_execution : False
max_text_history : 3
max_image_history : 1
max_cot_history : 3
feedback_on_invalid_action : True